---
title: "Catan Maths"
output: html_document
date: "2023-10-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### packages

```{r}


library(tidyverse)



```


```{r}

tile = c("brick", "brick", "brick","wheat", "wheat", "wheat", "wheat", 
         "farm", "farm", "farm", "farm", "wood", "wood", "wood", "wood", 
         "ore", "ore", "ore", "desert")


tile_tab = tibble(tile)

tile_tab1 = tile_tab %>% mutate(no = 1:n())


```



```{r}

selected_rows <- tile_tab1[sample(nrow(tile_tab1), 19, replace = FALSE), ]





```


```{r}



x = c(1:7)


gameboard = tibble(x) %>%
                  mutate(v = 7) %>%
                    uncount(v ) %>% 
                      group_by(x) %>%
                        mutate(y = 1:n())






```


```{r}


col = c(1:5)


gameboard2 = tibble(col) %>%
                  mutate(v = 5) %>%
                    uncount(v ) %>% 
                      group_by(col) %>%
                        mutate(row = 1:n()) %>%
                          mutate(type = if_else(row %in% c(1,5), 
                                                if_else(col %in%),2))


```